<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FitnessHouse.Application\FitnessHouse.Application.csproj" />
    <ProjectReference Include="..\FitnessHouse.Infrastructure\FitnessHouse.Infrastructure.csproj" />
    <ProjectReference Include="..\FitnessHouse.Domain\FitnessHouse.Domain.csproj" />
  </ItemGroup>

</Project>
